export type QuizDifficulty = 'Easy' | 'Medium' | 'Hard';

export type QuizQuestion = {
  id: string;
  image: string;
  question: string;
  options: string[];
  correctAnswer: number;
  points: number;
  classAssignment: string;
  verified: boolean;
  category: 'Guru Parampara' | 'Tug of War';
  subject: string;
  difficulty: QuizDifficulty;
  explanation: string;
};

export type TugOfWarSettings = {
  enabled: boolean;
  questionCount: number;
  timerDuration: number;
  category: 'Tug of War';
  classSelection: 'ALL' | 'CLASS 3' | 'CLASS 4' | 'CLASS 5' | 'CLASS 6' | 'CLASS 7';
  difficulty: 'ALL' | QuizDifficulty;
  randomQuestions: boolean;
};

export const defaultTugOfWarSettings: TugOfWarSettings = {
  enabled: true,
  questionCount: 10,
  timerDuration: 15,
  category: 'Tug of War',
  classSelection: 'ALL',
  difficulty: 'ALL',
  randomQuestions: true,
};

const tugImage = '/guru-assets/guru-maharaj.jpg';

export const initialQuestionBank: QuizQuestion[] = [
  {
    id: 'portrait-guru-maharaj',
    image: tugImage,
    question: 'Select the name belonging to the portrait shown above.',
    options: ['Guru Maharaj'],
    correctAnswer: 0,
    points: 20,
    classAssignment: 'CLASS 3',
    verified: false,
    category: 'Guru Parampara',
    subject: 'Gurukul',
    difficulty: 'Easy',
    explanation: 'This is the supplied Guru Maharaj visit portrait.',
  },
  {
    id: 'tug-01',
    image: tugImage,
    question: 'Which quality helps a team keep moving when a challenge feels difficult?',
    options: ['Patience', 'Distraction', 'Giving up', 'Blaming others'],
    correctAnswer: 0,
    points: 1,
    classAssignment: 'CLASS 3',
    verified: true,
    category: 'Tug of War',
    subject: 'Values',
    difficulty: 'Easy',
    explanation: 'Patience gives a team time to listen, learn, and try again.',
  },
  {
    id: 'tug-02',
    image: tugImage,
    question: 'What is the value of 7 × 8?',
    options: ['48', '54', '56', '64'],
    correctAnswer: 2,
    points: 1,
    classAssignment: 'CLASS 4',
    verified: true,
    category: 'Tug of War',
    subject: 'Mathematics',
    difficulty: 'Easy',
    explanation: 'Seven groups of eight make fifty-six.',
  },
  {
    id: 'tug-03',
    image: tugImage,
    question: 'Which part of a plant usually absorbs water from the soil?',
    options: ['Flower', 'Root', 'Fruit', 'Leaf'],
    correctAnswer: 1,
    points: 1,
    classAssignment: 'CLASS 5',
    verified: true,
    category: 'Tug of War',
    subject: 'Science',
    difficulty: 'Easy',
    explanation: 'Roots anchor the plant and absorb water and minerals from the soil.',
  },
  {
    id: 'tug-04',
    image: tugImage,
    question: 'Which word is closest in meaning to “brave”?',
    options: ['Courageous', 'Sleepy', 'Quiet', 'Careless'],
    correctAnswer: 0,
    points: 1,
    classAssignment: 'CLASS 6',
    verified: true,
    category: 'Tug of War',
    subject: 'English',
    difficulty: 'Easy',
    explanation: 'Courageous means showing courage or bravery.',
  },
  {
    id: 'tug-05',
    image: tugImage,
    question: 'What should we do before using a shared classroom resource?',
    options: ['Hide it', 'Ask and handle it carefully', 'Take it home', 'Leave it on the floor'],
    correctAnswer: 1,
    points: 1,
    classAssignment: 'CLASS 7',
    verified: true,
    category: 'Tug of War',
    subject: 'Gurukul Values',
    difficulty: 'Medium',
    explanation: 'Respectful sharing keeps resources safe and available to everyone.',
  },
  {
    id: 'tug-06',
    image: tugImage,
    question: 'Which fraction is equal to one half?',
    options: ['2/3', '3/5', '4/8', '5/8'],
    correctAnswer: 2,
    points: 1,
    classAssignment: 'CLASS 3',
    verified: true,
    category: 'Tug of War',
    subject: 'Mathematics',
    difficulty: 'Medium',
    explanation: 'Four divided by eight simplifies to one half.',
  },
  {
    id: 'tug-07',
    image: tugImage,
    question: 'Water changes into water vapour during which process?',
    options: ['Freezing', 'Evaporation', 'Condensation', 'Melting'],
    correctAnswer: 1,
    points: 1,
    classAssignment: 'CLASS 4',
    verified: true,
    category: 'Tug of War',
    subject: 'Science',
    difficulty: 'Medium',
    explanation: 'Evaporation happens when liquid water changes into vapour.',
  },
  {
    id: 'tug-08',
    image: tugImage,
    question: 'A group listens to every voice before deciding. What are they practising?',
    options: ['Teamwork', 'Impatience', 'Wastefulness', 'Silence'],
    correctAnswer: 0,
    points: 1,
    classAssignment: 'CLASS 5',
    verified: true,
    category: 'Tug of War',
    subject: 'Values',
    difficulty: 'Medium',
    explanation: 'Listening to each person is an important part of teamwork.',
  },
  {
    id: 'tug-09',
    image: tugImage,
    question: 'Which sentence uses the past tense?',
    options: ['The team practises.', 'The team will practise.', 'The team practised.', 'The team is practising.'],
    correctAnswer: 2,
    points: 1,
    classAssignment: 'CLASS 6',
    verified: true,
    category: 'Tug of War',
    subject: 'English',
    difficulty: 'Medium',
    explanation: '“Practised” describes an action that already happened.',
  },
  {
    id: 'tug-10',
    image: tugImage,
    question: 'If a rope position moves from 0 to -1, which side pulled it?',
    options: ['Student 1', 'Student 2', 'Both equally', 'Neither side'],
    correctAnswer: 0,
    points: 1,
    classAssignment: 'CLASS 7',
    verified: true,
    category: 'Tug of War',
    subject: 'Game Strategy',
    difficulty: 'Hard',
    explanation: 'Negative rope positions represent movement toward Student 1.',
  },
  {
    id: 'tug-11',
    image: tugImage,
    question: 'Which action best shows seva in a shared classroom?',
    options: ['Leaving a mess', 'Helping prepare the room', 'Interrupting others', 'Keeping all materials'],
    correctAnswer: 1,
    points: 1,
    classAssignment: 'CLASS 3',
    verified: true,
    category: 'Tug of War',
    subject: 'Gurukul Values',
    difficulty: 'Easy',
    explanation: 'Helping prepare a shared space is a simple act of service.',
  },
  {
    id: 'tug-12',
    image: tugImage,
    question: 'A triangle has angles of 60° and 70°. What is its third angle?',
    options: ['40°', '50°', '60°', '70°'],
    correctAnswer: 1,
    points: 1,
    classAssignment: 'CLASS 7',
    verified: true,
    category: 'Tug of War',
    subject: 'Mathematics',
    difficulty: 'Hard',
    explanation: 'The angles in a triangle total 180°, so 180 − 60 − 70 = 50°.',
  },
  {
    id: 'tug-13',
    image: tugImage,
    question: 'How many days are there in the month of February in a leap year?',
    options: ['27', '28', '29', '30'],
    correctAnswer: 2,
    points: 1,
    classAssignment: 'CLASS 3',
    verified: true,
    category: 'Tug of War',
    subject: 'General Knowledge',
    difficulty: 'Easy',
    explanation: 'In a leap year, February has 29 days instead of 28.',
  },
  {
    id: 'tug-14',
    image: tugImage,
    question: 'Which of these is a synonym for "happy"?',
    options: ['Joyful', 'Angry', 'Tired', 'Bored'],
    correctAnswer: 0,
    points: 1,
    classAssignment: 'CLASS 3',
    verified: true,
    category: 'Tug of War',
    subject: 'English',
    difficulty: 'Easy',
    explanation: '"Joyful" means feeling or showing great happiness.',
  },
  {
    id: 'tug-15',
    image: tugImage,
    question: 'What do we call the star at the centre of our solar system?',
    options: ['Moon', 'Sun', 'Mars', 'Comet'],
    correctAnswer: 1,
    points: 1,
    classAssignment: 'CLASS 4',
    verified: true,
    category: 'Tug of War',
    subject: 'Science',
    difficulty: 'Easy',
    explanation: 'The Sun is the star at the centre of our solar system.',
  },
  {
    id: 'tug-16',
    image: tugImage,
    question: 'What is 15 + 27?',
    options: ['32', '42', '52', '40'],
    correctAnswer: 1,
    points: 1,
    classAssignment: 'CLASS 4',
    verified: true,
    category: 'Tug of War',
    subject: 'Mathematics',
    difficulty: 'Easy',
    explanation: '15 + 27 = 42.',
  },
  {
    id: 'tug-17',
    image: tugImage,
    question: 'Speaking kindly to a guest is an example of which value?',
    options: ['Respect', 'Laziness', 'Pride', 'Selfishness'],
    correctAnswer: 0,
    points: 1,
    classAssignment: 'CLASS 4',
    verified: true,
    category: 'Tug of War',
    subject: 'Gurukul Values',
    difficulty: 'Easy',
    explanation: 'Speaking kindly to guests shows respect and good manners.',
  },
  {
    id: 'tug-18',
    image: tugImage,
    question: 'Which of these is a prime number?',
    options: ['9', '15', '17', '21'],
    correctAnswer: 2,
    points: 1,
    classAssignment: 'CLASS 5',
    verified: true,
    category: 'Tug of War',
    subject: 'Mathematics',
    difficulty: 'Medium',
    explanation: '17 has only two factors, 1 and itself, so it is prime.',
  },
  {
    id: 'tug-19',
    image: tugImage,
    question: 'Which gas do plants absorb from the air for photosynthesis?',
    options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'],
    correctAnswer: 2,
    points: 1,
    classAssignment: 'CLASS 5',
    verified: true,
    category: 'Tug of War',
    subject: 'Science',
    difficulty: 'Medium',
    explanation: 'Plants take in carbon dioxide from the air to make food.',
  },
  {
    id: 'tug-20',
    image: tugImage,
    question: 'Choose the correctly spelled word.',
    options: ['Recieve', 'Receive', 'Receeve', 'Receve'],
    correctAnswer: 1,
    points: 1,
    classAssignment: 'CLASS 5',
    verified: true,
    category: 'Tug of War',
    subject: 'English',
    difficulty: 'Medium',
    explanation: 'The correct spelling follows "i before e except after c": receive.',
  },
  {
    id: 'tug-21',
    image: tugImage,
    question: 'A team wins a tug of war mainly through which combination?',
    options: ['Strength alone', 'Luck alone', 'Coordination and effort', 'Loud shouting alone'],
    correctAnswer: 2,
    points: 1,
    classAssignment: 'CLASS 5',
    verified: true,
    category: 'Tug of War',
    subject: 'Game Strategy',
    difficulty: 'Medium',
    explanation: 'Working together with well-timed effort matters as much as strength.',
  },
  {
    id: 'tug-22',
    image: tugImage,
    question: 'What is the capital city of India?',
    options: ['Mumbai', 'Kolkata', 'New Delhi', 'Chennai'],
    correctAnswer: 2,
    points: 1,
    classAssignment: 'CLASS 6',
    verified: true,
    category: 'Tug of War',
    subject: 'General Knowledge',
    difficulty: 'Medium',
    explanation: 'New Delhi is the capital city of India.',
  },
  {
    id: 'tug-23',
    image: tugImage,
    question: 'What is the value of x if 3x = 27?',
    options: ['6', '7', '8', '9'],
    correctAnswer: 3,
    points: 1,
    classAssignment: 'CLASS 6',
    verified: true,
    category: 'Tug of War',
    subject: 'Mathematics',
    difficulty: 'Medium',
    explanation: 'Dividing both sides by 3 gives x = 9.',
  },
  {
    id: 'tug-24',
    image: tugImage,
    question: 'Which organ pumps blood throughout the human body?',
    options: ['Lungs', 'Heart', 'Kidney', 'Liver'],
    correctAnswer: 1,
    points: 1,
    classAssignment: 'CLASS 6',
    verified: true,
    category: 'Tug of War',
    subject: 'Science',
    difficulty: 'Medium',
    explanation: 'The heart pumps blood to carry oxygen and nutrients around the body.',
  },
  {
    id: 'tug-25',
    image: tugImage,
    question: 'Choosing to encourage a teammate who is losing shows which quality?',
    options: ['Jealousy', 'Compassion', 'Arrogance', 'Indifference'],
    correctAnswer: 1,
    points: 1,
    classAssignment: 'CLASS 6',
    verified: true,
    category: 'Tug of War',
    subject: 'Values',
    difficulty: 'Medium',
    explanation: 'Compassion means caring about others, even during a competition.',
  },
  {
    id: 'tug-26',
    image: tugImage,
    question: 'What is the square root of 144?',
    options: ['10', '11', '12', '14'],
    correctAnswer: 2,
    points: 1,
    classAssignment: 'CLASS 7',
    verified: true,
    category: 'Tug of War',
    subject: 'Mathematics',
    difficulty: 'Hard',
    explanation: '12 × 12 = 144, so the square root of 144 is 12.',
  },
  {
    id: 'tug-27',
    image: tugImage,
    question: 'Which force pulls the rope back toward the ground during a tug of war?',
    options: ['Magnetism', 'Gravity', 'Friction', 'Tension'],
    correctAnswer: 1,
    points: 1,
    classAssignment: 'CLASS 7',
    verified: true,
    category: 'Tug of War',
    subject: 'Science',
    difficulty: 'Hard',
    explanation: 'Gravity pulls objects, including a dropped rope, toward the ground.',
  },
  {
    id: 'tug-28',
    image: tugImage,
    question: 'Identify the figure of speech: "The wind whispered through the trees."',
    options: ['Simile', 'Personification', 'Rhyme', 'Alliteration'],
    correctAnswer: 1,
    points: 1,
    classAssignment: 'CLASS 7',
    verified: true,
    category: 'Tug of War',
    subject: 'English',
    difficulty: 'Hard',
    explanation: 'Giving the wind a human action, "whispered," is personification.',
  },
  {
    id: 'tug-29',
    image: tugImage,
    question: 'Which of the following best describes humility in a Gurukul setting?',
    options: ['Boasting about achievements', 'Accepting guidance with an open mind', 'Ignoring the teacher', 'Refusing to ask questions'],
    correctAnswer: 1,
    points: 1,
    classAssignment: 'CLASS 7',
    verified: true,
    category: 'Tug of War',
    subject: 'Gurukul Values',
    difficulty: 'Hard',
    explanation: 'Humility means staying open to learning and guidance from teachers.',
  },
  {
    id: 'tug-30',
    image: tugImage,
    question: 'Two teams pull with equal force on opposite ends of the rope. What happens to the marker?',
    options: ['It moves toward Team 1', 'It moves toward Team 2', 'It stays still', 'It moves in circles'],
    correctAnswer: 2,
    points: 1,
    classAssignment: 'CLASS 7',
    verified: true,
    category: 'Tug of War',
    subject: 'Game Strategy',
    difficulty: 'Hard',
    explanation: 'Equal and opposite forces cancel out, so the marker stays in place.',
  },
];